# Generated by Django 3.0.4 on 2020-05-25 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('DEC', 'declined'), ('PEN', 'pending')], default='PEN', max_length=31)),
            ],
            options={
                'verbose_name': 'invite',
                'db_table': 'invite',
            },
        ),
    ]
