# Generated by Django 3.0.4 on 2020-05-31 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_auto_20200525_2002'),
        ('invite', '0003_invite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
