# Generated by Django 3.0.4 on 2020-06-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200525_2002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0004_auto_20200601_1038'),
    ]

    operations = [
        migrations.RenameModel("Invite", "InviteUserToTeam")
    ]
