# Generated by Django 3.0.4 on 2020-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0005_auto_20200620_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteusertoteam',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inviteusertoteam',
            name='token_date_accepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inviteusertoteam',
            name='token_date_expired',
            field=models.DateTimeField(default='2020-05-25'),
            preserve_default=False,
        ),
    ]
