# Generated by Django 3.0.4 on 2020-05-25 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team_name', models.CharField(max_length=255)),
                ('creator_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'team',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_users', to='team.Team')),
            ],
            options={
                'verbose_name': 'user team',
                'db_table': 'user_team',
            },
        ),
    ]
