# Generated by Django 3.0.4 on 2020-04-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
